### ISSUE TITLE
组合输入框如何给每一个输入框单独这只后缀

### ISSUE THREAD

**Issue by xia930425** [fluent-form/fluent-form#148]
![image](https://github.com/fluent-form/fluent-form/assets/78598847/5499ad35-d3a3-42e6-ae4a-307caf0d9140)
如图所示

**Comment by HyperLife1119** [comment]
ng-zorro-antd 似乎还不支持此功能

**Comment by HyperLife1119** [comment]
应该可以通过一个假的输入框来实现后缀：

```ts
inputGroup().label('输入框组').col(6).schemas(() => {
      const fakeText = () => text('_').readonly(true).col(1).style({ padding: 0, textAlign: 'center' })
      text('week').col({ flex: 'auto' })
      fakeText().placeholder('周')
      text('day').col({ flex: 'auto' })
      fakeText().placeholder('天')
    })
```

![image](https://github.com/fluent-form/fluent-form/assets/41798664/dfc0d904-a820-4861-87aa-bf8380076c2d)

**Comment by xia930425** [comment]
> 应该可以通过一个假的输入框来实现后缀：
> 
> ```ts
> inputGroup().label('输入框组').col(6).schemas(() => {
>   const fakeText = () => text('_').readonly(true).col({ flex: '75px' }).style({ padding: 0, textAlign: 'center' })
>   text('week').col({ flex: 'auto' })
>   fakeText().placeholder('周')
>   text('day').col({ flex: 'auto' })
>   fakeText().placeholder('天')
> })
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/41798664/342316255-dfc0d904-a820-4861-87aa-bf8380076c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODI2ODgsIm5iZiI6MTcxOTI4MjM4OCwicGF0aCI6Ii80MTc5ODY2NC8zNDIzMTYyNTUtZGZjMGQ5MDQtYTgyMC00ODYxLTg3YWEtYmY4MzgwMDc2YzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAyMjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwY2M0MWFjMjE2ZTU3ODdhM2ZjYzgwMzkwMGFjOTQ0Zjg5MTQyMzk3NmZlOWNhODAyY2UxNWNlZDBjMzlhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rl1iM4zt3B_G8yydWVHze8lL2CZSA9V8gVQFAB7VcT0)

嗯 先用这个也不错。

**Comment by xia930425** [comment]
> ng-zorro-antd 似乎还不支持此功能
