### ISSUE TITLE
如何input等输入框如何触发点击事件

### ISSUE THREAD

**Issue by xia930425** [fluent-form/fluent-form#149]
如题

**Comment by HyperLife1119** [comment]
```ts
text().listeners({ click: () => {} })
```

**Comment by xia930425** [comment]
> 没读懂标题，你的意思是监听事件？
> 
> ```ts
> text().listeners({ click: () => {} })
> ```



> 没读懂标题，你的意思是监听事件？
> 
> ```ts
> text().listeners({ click: () => {} })
> ```

好的，那么在其他方法中，如何获取input值或者重新赋值？用model吗？

**Comment by HyperLife1119** [comment]
直接更新 model，或者通过 (formChange) 事件，拿到 formGroup 实例后直接操作表单

**Comment by xia930425** [comment]
我使用更新model方法，model内容确实更新了，但是页面中的输入框却还是没有任何值

**Comment by HyperLife1119** [comment]
show me code.

**Comment by xia930425** [comment]
https://stackblitz.com/edit/stackblitz-starters-duzqmn?file=src%2Fmain.ts，这是简化的代码。在这里面是没有问题的。但是在我实际业务中，每次值的变更，都要输入框失焦后内容才能显示在上面。

**Comment by HyperLife1119** [comment]
你没有复现出来的话，我这边也不太清楚了。
