### ISSUE TITLE
关于表单验证触发

### ISSUE THREAD

**Issue by xia930425** [fluent-form/fluent-form#150]
表单验证是如何触发的？如果用其他方法如何验证表单？

**Comment by HyperLife1119** [comment]
表单验证文档：https://fluent-form.github.io/fluent-form/ui-ant/control#%E8%A1%A8%E5%8D%95%E9%AA%8C%E8%AF%81

表单验证时机是根据 `updateOn` 设置来决定的：https://fluent-form.github.io/fluent-form/ui-ant/control#%E6%9B%B4%E6%96%B0%E6%97%B6%E6%9C%BA

如果想要主动触发验证，可以通过 (formChange) 事件或其他方式拿到 formGroup 实例，手动调用 `form.updateValueAndValidity()` 方法。

**Comment by xia930425** [comment]
除了 (formChange) 事件还有什么办法可以拿到 formGroup 实例？

**Comment by HyperLife1119** [comment]
例如在 schemas 里的事件侦听器里也能拿到表单实例：

```ts
.listeners({
   click: (event, context) => {
       context.control.root // <-- FormGroup
   }
})
```
