### ISSUE TITLE
select选择器如何联动获取选中的label值给其他输入框？

### ISSUE THREAD

**Issue by miao020622** [fluent-form/fluent-form#153]

**Comment by HyperLife1119** [comment]
目前没有直接提供 表单联动设置控件**值** 的功能，但是你可以通过手动设置值 来完成这一点，例如：

```ts
select('x')
  .label('控制值')
  .options(...)
  .listeners({
    valueChange: (value, { control }) => {
      // 给其他控件设置值
      control.parent?.get('y')?.setValue(value);
    }
  });

text('y').label('输入框');
```

另外，您可以分享一下你当前的场景/案例吗，或许我可以根据这一场景开发一个对应的功能来改进开发体验。
你这里所说的“其他输入框”，它们是**只读（readonly）**的吗？它们的值是否**只能**通过其他控件的值来自动设置？

**Comment by miao020622** [comment]
`select('opsDoctorCode')
          .col(3)
          .label('手术医生1')
          .required(true)
          .tips({ error: '请选择手术医生1' })
          .fetchOptions(key$ => key$.pipe(switchMap(key => this.fyHisDataService.getDocCard(key))))
          .listeners({
            valueChange: (value, { control }) => {
              console.log(value);
            }
          })
          .class('red_label');
        text('opsDoctor').hidden(true);`
        上文所述的‘其他输入框’是指隐藏的，该隐藏框是属于必填的，通过‘opsDoctorCode’选择器选择其中的key值赋值给‘opsDoctor’，opsDoctorCode数据格式是：Key(医生姓名) ：Value(身份证号)

**Comment by HyperLife1119** [comment]
好的，感谢你分享的案例。目前你还是需要通过 valueChange 手动设置其他控件的值，在后续版本中会添加一种跟便捷的用法来简化此类场景。

另外，我推荐你将

```ts
text('opsDoctor').hidden(true);
```

替换为：

```ts
headless('opsDoctor');
```
因为 `headless` 更适合用作“隐藏”的控件 :)

**Comment by miao020622** [comment]
好的感谢，可是valueChange手动设置只能拿到value值，貌似取不到key值，我再研究研究其他办法吧

**Comment by HyperLife1119** [comment]
目前没有直接获取 label 的方法，这里你可以将 getDocCard 的搜索结果通过一个 map 缓存起来，在 valueChange 中通过 value 来查找

**Comment by HyperLife1119** [comment]
Close via 1e3c69760f05abbabeaaf8f7480de0e75d55f0b4.
